### PR TITLE
Fixed grammar and spelling

### PR DESCRIPTION
**Pull request by rowmatrix**
For issue #1 
If you have any questions just let me know.

### CODE REVIEW

**Review by xzinkus — CHANGES_REQUESTED** [review]
This probably won't merge nicely after #2 is merged, please fork DeltaHeavy/image_processing and I'll merge you onto there before we both merge onto master. Thank you!

**Comment by rowmatrix** [comment]
@DeltaHeavy  Alright no problem
Did I do it right?

**Comment by xzinkus** [comment]
I'm not seeing the PR against https://github.com/DeltaHeavy/image_processing/pulls make sure open it there, thanks! You the best :+1:

**Comment by rowmatrix** [comment]
@DeltaHeavy It should be there now
@DeastinY You can close this PR and merge with PR #2 once @DeltaHeavy is finished

**Comment by DeastinY** [comment]
Will be done, thanks !

**Pull request closed without merging**
